name: "Please Star First"
author: "uhyo"
description: "Automatically closes issues opened by non-stargazers"
branding:
  icon: star
  color: yellow
inputs:
  token:
    description: "GitHub token for use by this action."
    required: false
    default: ${{ github.token }}
  message:
    description: "Message"
    required: false
    default: |
      Please star this repository before opening an issue.

      Thanks!
runs:
  using: "node20"
  main: "dist/index.js"
