on:
  issues:
    types: [opened, reopened]

jobs:
  greet:
    runs-on: ubuntu-latest
    name: Close issue opened by non-stargazer
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: close
        uses: ./
